# Build the image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/saurav-cicd/gke-repo/quickstart-image', './app1']
  id: 'Build Docker Image'
  
#step->gcloud beta artifacts repositories create gke-repo --repository-format=docker --location=us-central1

# Push the image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/saurav-cicd/gke-repo/quickstart-image']
  id: 'Push Docker Image to GCR'
  
# Build the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/saurav-cicd/gke-repo/flask-image', './app2' ]
  id: 'Build Docker Image2'

# Push the image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/saurav-cicd/gke-repo/flask-image' ]
  id: 'Push Docker Image2'

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY

